### ISSUE TITLE
Export macro test_vfs

### ISSUE THREAD

**Issue by der-b** [manuel-woelker/rust-vfs#18]
If the vfs is extended by in another crate as suggested [here](https://github.com/manuel-woelker/rust-vfs/pull/16), than the macro test_vfs! can't be used from the other crate, since it is only [available for the tests](https://github.com/manuel-woelker/rust-vfs/blob/master/src/lib.rs#L53). It would be nice, if this macro can be exported for the use within other crates. My be it can be exported as a feature?

At least, I didn't found any possibility to access the macro from an other crate.

**Comment by manuel-woelker** [comment]
Good point, thanks for the suggestion. It should be possible to export this with a feature gate. I will take a look at this tomorrow.

**Comment by manuel-woelker** [comment]
Should work now in 0.5.1, please let me know if there are any issues. Cheers!

**Comment by der-b** [comment]
Thanks, but there is still an issue: The macro tries to import [VfsPath](https://github.com/manuel-woelker/rust-vfs/blob/master/src/test_macros.rs#L9) and [VfsFileType](https://github.com/manuel-woelker/rust-vfs/blob/master/src/test_macros.rs#L8) from the current crate. Obviously, these are only available in VFS and not in other crates. I don't have an idea, how to solve this. Maybe the caller has to import these types?

**Comment by manuel-woelker** [comment]
Could you try with ad1c22e98b98157fe0b3f5167475592875b62e1b, I changed the use declaration to use $crate, which might fix the issue.

https://doc.rust-lang.org/reference/macros-by-example.html#hygiene

**Comment by der-b** [comment]
Great! Now it works!

**Comment by manuel-woelker** [comment]
Good to hear! Do you want me to publish another patch version so you don't have to depend on a git commit id?

**Comment by der-b** [comment]
Yes, that would be great.
